import { NextResponse } from "next/server";
import { auth, currentUser } from "@clerk/nextjs/server";
import { db } from "@/lib/db";
import { startOfDay, format } from "date-fns";
import { toZonedTime } from "date-fns-tz";
import nodemailer from "nodemailer";

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return new NextResponse("Unauthorized", { status: 401 });
    }
    const user = await currentUser();
    const userName = user?.firstName || "Your partner";

    const partner = await db.accountabilityPartner.findUnique({
      where: { userId },
    });

    if (!partner) {
      return new NextResponse("Accountability partner required", { status: 400 });
    }

    // Server time in IST
    const now = new Date();
    const istTime = toZonedTime(now, "Asia/Kolkata");
    const eventDate = startOfDay(istTime);

    // Check if an event already exists
    const existing = await db.habitEvent.findFirst({
      where: {
        userId,
        eventDate: eventDate,
      },
    });

    if (existing) {
      // For testing purposes: Delete the old event instead of blocking
      await db.habitEvent.delete({ where: { id: existing.id } });
    }

    // 1. Create RELAPSE event
    const event = await db.habitEvent.create({
      data: {
        userId,
        type: "RELAPSE",
        eventDate: eventDate,
        occurredAt: now,
      },
    });

    // 2. Create Notification record (PENDING)
    const notification = await db.notification.create({
      data: {
        eventId: event.id,
        recipient: partner.email,
        type: "EMAIL",
        status: "PENDING",
      },
    });

    // 3. Send email inline using Nodemailer
    const formattedDate = format(istTime, "MMMM do, yyyy");
    const formattedTime = format(istTime, "h:mm a");

    let finalStatus = "SENT";
    try {
      const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_APP_PASSWORD,
        },
      });

      await transporter.sendMail({
        from: `"Accountability Tracker" <${process.env.EMAIL_USER}>`,
        to: partner.email,
        subject: "Accountability Alert",
        text: `${userName} recorded a relapse.\n\nDate: ${formattedDate}\nTime: ${formattedTime} IST\n\nThis notification was automatically generated by the Accountability Tracker.`,
      });

      // 4. Update Notification to SENT
      await db.notification.update({
        where: { id: notification.id },
        data: {
          status: "SENT",
          sentAt: new Date(),
        },
      });
    } catch (emailError) {
      console.error("Failed to send email:", emailError);
      finalStatus = "FAILED";
      // Update Notification to FAILED
      await db.notification.update({
        where: { id: notification.id },
        data: {
          status: "FAILED",
        },
      });
    }

    return NextResponse.json({ event, notificationStatus: finalStatus });
  } catch (error) {
    console.error("[EVENT_RELAPSE_POST]", error);
    return new NextResponse("Internal Error", { status: 500 });
  }
}
